version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    image: jewels/catalogapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabaseUserPassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:5060
    ports:
      - "5060:80"
    container_name: catalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: jewels/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://10.10.10.30:5070
      ConnectionString: basket.data
    ports:
      - "5065:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: jewels/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://10.10.10.30:5070
      SQLSERVER_HOST: catalogdb
      SA_PASSWORD: ProductApi(!)
      DATABASE: OrdersDb
    ports:
      - "5075:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5202
    ports:
      - "5070:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: jewels/webmvc
    container_name: webshop
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://10.10.10.30:5070
      CallBackUrl: http://localhost:5202
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_jZlpubvlPmcV6QJPReImelQy
      StripePrivateKey: sk_test_bSHT9qxwjpyCOP0qdAvHLfAA
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5202:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart
      - order


  mssqlserver:
    image:  "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: catalogdb
    ports:
      - "1448:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6378:6379"  
    networks:
      - backend 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 